#!/bin/sh

work_tree=/var/cache/a_trading_system
deployment_dir=/srv/a-trading-system/current

rsync -a "${work_tree}/_build/prod/rel/a_trading_system/" "$deployment_dir"
sudo /bin/systemctl restart a-trading-system

