# This file is responsible for configuring your application
# and its dependencies with the aid of the Config module.
#
# This configuration file is loaded before any dependency and
# is restricted to this project.

# General application configuration
import Config

config :a_trading_system,
  generators: [timestamp_type: :utc_datetime]

# Configures the endpoint
config :a_trading_system, ATradingSystemWeb.Endpoint,
  check_origin: false,
  debug_errors: true,
  url: [host: "localhost"],
  server: false,
  adapter: Bandit.PhoenixAdapter,
  render_errors: [
    formats: [html: ATradingSystemWeb.ErrorHTML, json: ATradingSystemWeb.ErrorJSON],
    layout: false
  ],
  https: [cipher_suite: :strong],
  pubsub_server: ATradingSystem.PubSub,
  live_view: [signing_salt: "gM8h9+M5"],
  # Note we also include the path to a cache manifest
  # containing the digested version of static files. This
  # manifest is generated by the `mix assets.deploy` task,
  # which you should run after static files are built and
  # before starting your production server.
  cache_static_manifest: "priv/static/cache_manifest.json"

# Configure esbuild (the version is required)
config :esbuild,
  version: "0.17.11",
  a_trading_system: [
    args:
      ~w(js/app.js --bundle --target=es2017 --outdir=../priv/static/assets --external:/fonts/* --external:/images/*),
    cd: Path.expand("../assets", __DIR__),
    env: %{"NODE_PATH" => Path.expand("../deps", __DIR__)}
  ]

# Configure tailwind (the version is required)
config :tailwind,
  version: "3.4.3",
  a_trading_system: [
    args: ~w(
      --config=tailwind.config.js
      --input=css/app.css
      --output=../priv/static/assets/app.css
    ),
    cd: Path.expand("../assets", __DIR__)
  ]

# Configures Elixir's Logger
config :logger, :console,
  format: "$time $metadata[$level] $message\n",
  metadata: [:request_id]

config :logger, level: :info

# Use Jason for JSON parsing in Phoenix
config :phoenix, :json_library, Jason

# Initialize plugs at runtime for faster test compilation
config :phoenix, :plug_init_mode, :runtime

# FakeServer for test broker connectivity
config :a_trading_system, api_base_url: "http://localhost:8001"

# Enable dev routes for dashboard and mailbox
config :a_trading_system, dev_routes: true
# Import environment specific config. This must remain at the bottom
# of this file so it overrides the configuration defined above.
if config_env() == :dev, do: import_config("#{config_env()}.exs")
